In [1]:
import numpy as np

In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a=np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
a.size

6

In [7]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape=(3,2)

In [10]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [23]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
b.shape

(4, 3)

In [30]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
b.shape=(3,4)

In [28]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
############### Function using numpy ############

In [34]:
x=np.arange(1,7)

In [35]:
x

array([1, 2, 3, 4, 5, 6])

In [36]:
x.shape

(6,)

In [37]:
x=np.arange(1,7).reshape(2,3)

In [38]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
y= np.arange(7,13).reshape(2,3)

In [41]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [43]:
z= np.concatenate((x,y))

In [44]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
x=np.arange(1,7).reshape(3,2)

In [48]:
y= np.arange(7,13).reshape(2,3)

In [49]:
z= np.concatenate((x,y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [45]:
m = np.hstack((x,y))

In [46]:
m

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [57]:
m=np.vstack((x,y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [54]:
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
q= np.array([1,2,3,4,5,6])
np.vstack((q))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [58]:
ap= np.array([1,2,3,4,5])

In [59]:
ap=np.append(ap,[7,8,9])

In [60]:
ap

array([1, 2, 3, 4, 5, 7, 8, 9])

In [61]:
ap=np.append(ap,[10])

In [62]:
ap

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

In [71]:
mn = np.array([2,3,4,5])

In [72]:
mn

array([2, 3, 4, 5])

In [73]:
mn=np.insert(mn,0,1)

In [74]:
mn

array([1, 2, 3, 4, 5])

In [75]:
mn=np.insert(mn,3,7)

In [76]:
mn

array([1, 2, 3, 7, 4, 5])

In [77]:
mn = np.delete(mn,[0,3])

In [79]:
mn

array([2, 3, 4, 5])